version: '2'
services:
  app:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/personal-site
    ports:
      - "3000:3000"
    environment:
      # RAILS ENVIRONMENT
      - RAILS_ENV=development
